name: 🤖 Verify links

on: [push, pull_request]

jobs:
  verify_links:
    name: 🤖 Verify links
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: ⬇ Checkout
        uses: actions/checkout@v6

      - name: 🔧 Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: 🔧 Install dependencies
        run: |
          gem install awesome_bot
      - name: 🤖 Run Awesome Bot
        run: awesome_bot README.md --allow-redirect --white-list awesome.re
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: ab-results
          path: ab-results-README.md-filtered.json
